version: "3.5"
services:
  nginx:
    volumes:
      - ./:/var/www/html/wannabe
    environment:
      - AUTH_COOKIE_KEY

  app:
    build:
      target: development
    volumes:
      # Mount entire local app folder for development usage
      - ./:/var/www/html/wannabe
    networks:
      - wannabe_public
      - wannabe_internal
    environment:
      - APP_ENV=development

  mysql:
    image: mysql:5.7
    command: mysqld --sql_mode=""
    volumes:
       - mysql_data:/var/lib/mysql
       - ./sql/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    networks:
      - wannabe_internal

volumes:
  mysql_data:
