FROM debian:buster
WORKDIR /var/www/html/wannabe

# PHP and tooling
RUN apt-get update && apt-get install -y \
    php7.3 \
    apache2 \
    php7.3-mysql \
    php7.3-gd \
    php7.3-dom \
    python3-dev \
    libmariadbclient-dev \
    python3-pip \
    python3-mysqldb \
    vim \
    man \
    zip \
    unzip

# Python - migration requirements
COPY ./migrate/requirements.txt ./migrate/
RUN pip3 install -r ./migrate/requirements.txt

# Apache
RUN usermod -u 1000 www-data && groupmod -g 1000 www-data
RUN a2enmod rewrite
COPY build/wb-dev-apache2.conf /etc/apache2/sites-available/
RUN a2ensite wb-dev-apache2
RUN a2dissite 000-default

# Composer - CakePHP requirements
COPY --from=composer /usr/bin/composer /usr/bin/composer
COPY composer.* ./
# Remove lock file since it's currently configured for PHP 5
RUN rm ./composer.lock
RUN composer install --no-interaction

# App
COPY . .

# Startup
COPY build/wannabe-entrypoint.sh /usr/bin/wannabe-entrypoint
COPY build/wannabe-entrypoint-php7.sh /usr/bin/wannabe-entrypoint-php7
RUN chmod a+x /usr/bin/wannabe-entrypoint
RUN chmod a+x /usr/bin/wannabe-entrypoint-php7
ENTRYPOINT ["wannabe-entrypoint-php7"]

# TODO: Optional optimized production step
# FROM alpine:... AS Production
# ...
# COPY --from=builder /var/www/html/wannabe/app /var/www/html/wannabe
# ...
# CMD ["apache2-foreground"]
