version: "3.5"
services:
  app:
    build: .
    ports:
      - "4000:80"
    volumes:
      - .:/var/www/html/wannabe
    environment:
      - MYSQL_URL=mysql
      - MYSQL_USERNAME=wannabe
      - MYSQL_PASSWORD=wannabe
      - AUTH_COOKIE_KEY=if-you-see-me-in-prod-run-away
    restart: "no"

  mysql:
    image: mysql:5.7
    command: mysqld --sql_mode=""
    volumes:
       - mysql_data:/var/lib/mysql
       - ./sql/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER=wannabe
      - MYSQL_PASSWORD=wannabe
      - MYSQL_ROOT_PASSWORD=wannabe
      - MYSQL_DATABASE=wannabe

volumes:
    mysql_data:
