version: "3.5"
services:
  nginx:
    volumes:
      - ./:/var/www/html/wannabe
    environment:
      - MYSQL_URL=mysql
      - MYSQL_USERNAME=wannabe
      - MYSQL_PASSWORD=wannabe
      - AUTH_COOKIE_KEY=if-you-see-me-in-prod-run-away

  app:
    build:
      target: development
    volumes:
      # Mount entire local app folder for development usage
      - ./:/var/www/html/wannabe
    networks:
      - wannabe_public
      - wannabe_internal
    environment:
      - APP_ENV=development
      - LOG_ENGINE=console

  mysql:
    image: mysql:5.7
    command: mysqld --sql_mode=""
    volumes:
       - mysql_data:/var/lib/mysql
       - ./sql/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER=wannabe
      - MYSQL_PASSWORD=wannabe
      - MYSQL_ROOT_PASSWORD=wannabe
      - MYSQL_DATABASE=wannabe
    networks:
      - wannabe_internal

volumes:
  mysql_data:
